- Jenkinsfile
Fixing a bug/syntax error within the Jenkins pipeline created by the converters update.
> feature/cld-385: fixed boolean check for ML converters -z flag

- README.md
added steps to backup/restore a db
> CLD-393: Document any difference backup/recovery and upgrades procedure in the ML Docker Func Spec 

- README.md
added steps on how to upgrade ml release/version in docker
> CLD-387: Docs: Upgrading MarkLogic cluster in Docker

- README.md
Added steps to rotate secrets using docker stack for a multi-node cluster.
> CLD-455: Update Docker Readme for Secrets and Stack Instructions

- Jenkinsfile
- README.md
- src/centos/Makefile
- test/README.md
- test/docker-test-cases.json
* Replace all instances of yml with yaml
* Fix docker test cases
* Increase wait and add port to report output
Co-authored-by: Vitaly Korolev <vkorolev@marklogic.com>
> Feature/CLD-420 (#81)

- README.md
- docker-compose/marklogic-centos.yaml
- docker-compose/marklogic-cluster-centos.yaml
- Add hostname parameter to compose examples
- Backport hotfix changes from master
> Feature/CLD-453 & CLD-506

- src/centos/scripts/start-marklogic.sh
Additionally, changed = to == for all lexicographical comparisons.
> CLD-488: Change join cluster logic based on feedback

- Jenkinsfile
- README.md
- docker-compose/marklogic-centos.yaml
- docker-compose/marklogic-cluster-centos.yaml
- test/docker-test-cases.json
- Add image cleanup step
- Make sure job doesn't fail when jira comment fails
- Add scheduled build for develop branch
- Backport hotfix from master
- Fix string replace to update all image tags
- Fix uninitialized test case
> Combined CLD-499 CLD-506 CLD-508

- README.md
- docker-compose/marklogic-centos.yml
- docker-compose/marklogic-cluster-centos.yml
Increment version in README and compose yaml files. Also fix EA number in yaml files.
> Update version for 10.0-9.2 release

- README.md
- dockerFiles/marklogic-server-centos:base
- src/centos/scripts/start-marklogic.sh
- test/docker-test-cases.json
- added env var support
- added docker test case
> CLD-487: Add support for wallet password and realm in docker init

- dockerFiles/marklogic-server-centos:base
Sorry for the deletion and recreation of this PR, I had some issues with pushing updates to that PR
> CLD-530: Remove MLCMD from Docker images

- Jenkinsfile
Co-authored-by: Vitaly Korolev <vkorolev@marklogic.com>
> CLD-497 Use 11.0 builds until we fix 10.0-9 (#119)

- Jenkinsfile
Co-authored-by: Vitaly Korolev <vkorolev@marklogic.com>
> CLD-563 Add scheduled build for develop branch. (#142)

- Jenkinsfile
Harmless comment in the wrong spot is breaking Docker builds
> CLD-576 Bug fix in publish step of the pipeline

- Jenkinsfile
Co-authored-by: Vitaly Korolev <vkorolev@marklogic.com>
> CLD-577 Use alternate BRE character for sed replacements

- Jenkinsfile
Replace -1 with -rhel in 11.0 RPM
> CLD-621: Update Docker pipeline to use new RPM format

- Jenkinsfile
Fix invalid email format in Jenkinsfile.
> Fix invalid email format in Jenkinsfile

- src/centos/scripts/start-marklogic.sh
CLD-614: instance-admin should only be called on the bootstrap host
CLD-645: Implement ready check after bootstrap host initialization
> CLD-614 & CLD-645: Fix bugs related to initializing instance admin

- README.md
- docker-compose/marklogic-centos.yaml
- docker-compose/marklogic-cluster-centos.yaml
Update image tags to the latest image for ML11
> Version update for ML11 release

- Jenkinsfile
> CLD-657: Readme updates for Docker 1.0.1 release

- dockerFiles/marklogic-deps-centos:base
- [ X] JIRA_ID as part of branch/PR name
- [ X] Rebase the branch with upstream
- [X ] Squashed all commits into a single commit
- [ X] Added Tests
> remove ntp install and network config

- src/centos/scripts/start-marklogic.sh
> CLD-685: Bugfix code changes commit

- Jenkinsfile
CLD-696 was likely due to invalid variable reference which is now removed
Also removed server regression stage as it's currently an independent pipeline
Removed Ilan from the mailing list
> CLD-696 fix bug and clean up the pipeline

- README.md
> CLD-668: Upgrade instructions for docker should set MARKLOGIC_INIT=false

- src/centos/scripts/start-marklogic.sh
- test/compose-test-4.yaml
- test/compose-test-5.yaml
- test/compose-test-8.yaml
- test/compose-test-9.yaml
- test/docker-tests.robot
> CLD-744: added checks for bootstrap host & CLD-684

- README.md
- src/centos/scripts/start-marklogic.sh
- test/compose-test-4.yaml
- test/compose-test-5.yaml
- test/compose-test-8.yaml
- test/compose-test-9.yaml
- test/docker-tests.robot
- test/keywords.resource
changes for cld-744/684: improved logging and validation for bootstrap host
> CLD-744: added checks for bootstrap host & CLD-684 (#210)

- Jenkinsfile
Switch from @marklogic to @progress in the pipeline to fix mail delivery.
> CLD-817 Update email domain to progress.

- Jenkinsfile
The next default release is 11.1 and consequently the default branch should be updated to develop-11.1
> CLD-854 update default branch

- Jenkinsfile
- README.md
- dockerFiles/marklogic-server-centos:base
- src/centos/scripts/start-marklogic.sh
- test/compose-test-1.yaml
- test/compose-test-10.yaml
- test/compose-test-11.yaml
- test/compose-test-12.yaml
- test/compose-test-13.yaml
- test/compose-test-14.yaml
- test/compose-test-15.yaml
- test/compose-test-2.yaml
- test/docker-tests.robot
- test/get_ca_xquery.xqy
- test/keywords.resource
- test/test_template.json
> CLD-746: Add support for using HTTPS for the admin and management calls (Docker)

- src/centos/scripts/start-marklogic.sh
- [ X] JIRA_ID as part of branch/PR name
- [ X] Rebase the branch with upstream
- [X ] Squashed all commits into a single commit
> change logs output for secret

- README.md
> CLD-692 : add image tag in README

- Jenkinsfile
- dockerFiles/marklogic-server-centos:base
- test/structure-test.yaml
Increment Docker version for 1.1.0 release
> CLD-897 Increment Docker version for release

- Jenkinsfile
- dockerFiles/marklogic-server-centos:base
- src/centos/scripts/start-marklogic.sh
- test/structure-test.yaml
Update curl retry to remove debug curl output, but still capture the last response in a log file.
> CLD-910 remove debug output from startup log

- Jenkinsfile
MarkLogic version needs to be updated in the pipeline to match the latest 11 develop.
> Update MarkLogic 11 version to the latest

- Jenkinsfile
- Makefile
- dockerFiles/marklogic-deps-centos:base
- dockerFiles/marklogic-deps-ubi:base
- dockerFiles/marklogic-server-ubi:base
- src/centos/scripts/start-marklogic.sh
- src/scripts/start-marklogic.sh
> CLD-913: MarkLogic UBI-8 Docker Image Changes Commit

- dockerFiles/marklogic-deps-centos:base
> CLD-948: Adding two missing libraries for MarkLogic Converters

- Jenkinsfile
- Makefile
- dockerFiles/marklogic-deps-centos:base
- src/scripts/start-marklogic-rootless.sh
Modify pipeline to build, test and publish UBI and UBI-rootless images.
> MLE-4183 support ubi and rootless

- src/centos/scripts/start-marklogic.sh
> MLE-11012 logging issue when enable https

- Jenkinsfile
Due to changes in AWS CLI our pipeline is failing to push images to ECR.
> MLE-12105 fix ecr publish

- src/centos/scripts/start-marklogic.sh
> MLE-11596 Bug fix for bootstrap restart fail

- .gitignore
- Jenkinsfile
- Makefile
- dockerFiles/marklogic-server-ubi-rootless:base
- dockerFiles/marklogic-server-ubi:base
- hadolint.yaml
- src/scripts/start-marklogic-rootless.sh
- test/README.md
- test/docker-tests.robot
- test/keywords.resource
- test/structure-test.yaml
- Update docker tests to ignore OVERWRITE_ML_CONF and TZ parameter for rootless image
- Update structure tests to check for different PID file in case of rootless
- Update structure test to version 1.16.0 (should fix junit formatting as well so the workaround is removed)
- Update hadolint to ignore explicit yum version requirement
- Update robot syntax based on latest requirements
> MLE-11923 update docker tests

- dockerFiles/marklogic-deps-ubi:base
> Update libnsl package in UBI

- Jenkinsfile
- dockerFiles/marklogic-server-centos:base
- dockerFiles/marklogic-server-ubi-rootless:base
- dockerFiles/marklogic-server-ubi:base
- test/structure-test.yaml
increment docker ver to the latest release
> MLE-11680_update_docker_version

- Jenkinsfile
add latest tag to docker image
> MLE-12452 add latest tag

- Jenkinsfile
Update Jira URL and add docker pull command for convenience.
> MLE-13388 update Jira URL

- README.md
> MLE-13695 : Add Container Runtime Detection

- Jenkinsfile
- Makefile
- test/docker-tests.robot
- test/keywords.resource
- Added tests for docker image(root) upgrade
> MLE:13840: Implement test to verify ML Docker image upgrade

- Jenkinsfile
> MLE-14041: added default upgrade image to fix bug

- dockerFiles/marklogic-deps-ubi:base
> MLE-14110: Libnsl dependency changes commit

- src/scripts/start-marklogic-rootless.sh
- src/scripts/start-marklogic.sh
- test/docker-tests.robot
Startup script logic didn't work properly with MARKLOGIC_INIT with no value. Fixed and added a corresponding test.
> MLE-14090 init loop fix

- Jenkinsfile
When this pipeline triggers QA build, it doesn't work with ML10 and ML12. This PR should fix this.
> MLE-14125 fix qa build trigger

- README.md
Add steps to upgrade to rootless container
> MLE-13929: Add steps to upgrade to rootless container

- dockerFiles/marklogic-server-ubi-rootless:base
> MLE-14177 rootless fix

- src/scripts/start-marklogic-rootless.sh
- src/scripts/start-marklogic.sh
- test/docker-tests.robot
- test/keywords.resource
* Add test for converter installation
* Simplify startup logic when init is false for compatibility with Kubernetes
> MLE-4199 MLE-14141 converter test and init logic

- README.md
Add less to the known issues list
> MLE-13942 update issues

- Jenkinsfile
Increment Docker version to 2.0.0 before the release
> MLE-13332 update docker version

- CONTRIBUTING.md
- [ X] JIRA_ID as part of branch/PR name
- [ X] Rebase the branch with upstream
- [ NA] Squashed all commits into a single commit
- [ NA] Added Tests
- [ NA] Reviewed Tests
- [ NA] Added to Release Wiki/Jira
> MLE-4196 : Add Contributing file

- dockerFiles/marklogic-deps-ubi:base
> MLE-14318: UBI Minimal Image version update to 8.9 

- README.md
- [N/A] Rebase the branch with upstream
- [N/A] Squashed all commits into a single commit
- [N/A] Added Tests
> MLE-14478/Incorrect folder reference in README upgrade instructions

- NOTICE.txt
This PR is to update NOTICES.txt to the latest known version.
> MLE-14721 Update NOTICE.txt

- Makefile
- dockerFiles/marklogic-server-ubi-rootless:base
- dockerFiles/marklogic-server-ubi:base
- test/structure-test.yaml
Adding NOTICE.txt to home folder of the container user and a simple test to verify the existence of the file.
> MLE-14479 add notice file to docker images

- README.md
- docker-compose/marklogic-multi-node.yaml
- docker-compose/marklogic-single-node.yaml
- dockerFiles/marklogic-server-centos:base
- dockerFiles/marklogic-server-ubi-rootless:base
- dockerFiles/marklogic-server-ubi:base
- test/README.md
- test/compose-test-1.yaml
- test/compose-test-10.yaml
- test/compose-test-11.yaml
- test/compose-test-12.yaml
- test/compose-test-13.yaml
- test/compose-test-14.yaml
- test/compose-test-15.yaml
- test/compose-test-2.yaml
- test/compose-test-3.yaml
- test/compose-test-4.yaml
- test/compose-test-5.yaml
- test/compose-test-6.yaml
- test/compose-test-7.yaml
- test/compose-test-8.yaml
- test/compose-test-9.yaml
Switching from marklogicdb/marklogic-db to progressofficial/marklogic-db
> MLE-14797 repo migration

- dockerFiles/marklogic-deps-ubi9:base
- dockerFiles/marklogic-deps-ubi:base
> MLE-16101/fips compliance

- dockerFiles/marklogic-deps-ubi9:base
- dockerFiles/marklogic-deps-ubi:base
> MLE-18064: updated ubi8 and ubi9 images to lates available

- README.md
- dockerFiles/marklogic-deps-ubi9:base
- dockerFiles/marklogic-deps-ubi:base
> MLE-18560/UPDATE-README-FIPS-HARDENING

- dockerFiles/marklogic-deps-ubi9:base
- dockerFiles/marklogic-deps-ubi:base
For UBI9, hostname is not included, add hostname for the dependency will fix the issue
> MLE-20695 Add Hostname for UBI9 dependency

- test/compose-test-16.yaml
- test/docker-tests.robot
- test/keywords.resource
This adds the automated testing for the dynamic host feature.
> MLE-20318: added test automation for the MarkLogic dynamic host feature.

- .github/workflows/pr-workflow.yaml
> PDP-473:Create pr-workflow.yaml

- Jenkinsfile
> MLE-17995/Add-Nightly-Tag

- Jenkinsfile
- [ X] JIRA_ID as part of branch/PR name
> MLE-17995/ remove code in error

- Jenkinsfile
> MLE-17995: merging changes from Develop to relase 2.2.0 branch

- Jenkinsfile
- dockerFiles/marklogic-deps-ubi9:base
- dockerFiles/marklogic-deps-ubi:base
- test/keywords.resource
> MLE-19522: updated version to 2.2.0 and ubi8 & ubi9 images latest

- Jenkinsfile
> MLE-23145/deactivate-pushing-to-Perf-team

- Jenkinsfile
- test/keywords.resource
> MLE-24406: updating release version 2.2.1 in develop branch

- Jenkinsfile
- test/keywords.resource
> MLE-23629: merging Release/docker 2.2.2 to develop
